### ISSUE TITLE
Size of coefficient array

### ISSUE THREAD

**Issue by beatsnbytes** [cbouilla/libfes-lite#1]
Hello, 
I would like to ask you why the size of the coefficient matrix is formed from the equation 1+n+n*(n-1)/2 where n is the number of variables if I understand correctly. In my case I have a matrix W(4X5) where I have 4 equations with 5 variables. The degree of the polynomials is 1 and my LSE is underdetermined. Is the libFES of any use at my case?
Thank you very much.
Vatistas

**Comment by beatsnbytes** [comment]
So I figured out my previous question. My next question now is: This lite software version does not support the functionality of the version that was embodies in Sage software right? Since it only accepts the coefficient matrix for quadratic forms I am not able to express x+y+z=0 ? Or if yes, then how?

**Comment by cbouilla** [comment]
Libfes-lite is indeed limited to polynomials of degree <= 2. But you can express linear equations by setting all the quadratic terms to zero. However, using exhaustive search is a VERY expensive way to solve linear equations!
What is your input problem, exactly?

**Comment by beatsnbytes** [comment]
Hello cbouilla, 
Indeed this was an expensive alternative to solve the LSE that I needed. Thank you for the help anyways and congrats for the project you got here!
